# yaml file to store the configurations
# changed it up to fit the configuration of the MOCO mod quadruped
# -Roy

# Robot structure parameters
hip_link_length: 0.045           # 45 mm   (JOINT TO JOINT)
upper_leg_link_length: 0.0861    # 86.1 mm (JOINT TO JOINT)
lower_leg_link_length: 0.0951    # 95.1 mm (JOINT TO JOINT)
body_width: 0.065                # 8.5 cm  (JOINT TO JOINT: 6.5 cm)
body_length: 0.075               # 11 cm   (JOINT TO JOINT: 7.5 cm)

# Stance parameters
default_stand_height: 0.155
stand_front_x_offset: 0.015
stand_back_x_offset:  0.0
lie_down_height: 0.083
lie_down_foot_x_offset: 0.065 

# Servo parameters
num_servos: 12
servo_max_angle_deg: 82.5
# servo num, center PWM val, range, direction, center angle at center PWM value
RF_3: {num: 1,  center: 280,range: 193,direction: -1, center_angle_deg:   44.6} # knee
RF_2: {num: 2,  center: 170,range: 211,direction:  1, center_angle_deg:  -50.9} # shoulder
RF_1: {num: 3,  center: 254,range: 560,direction:  1, center_angle_deg:  -22.4} # hip
RB_3: {num: 4,  center: 280,range: 187,direction: -1, center_angle_deg:   45.9} # knee
RB_2: {num: 5,  center: 160,range: 180,direction:  1, center_angle_deg:  -46.8} # shoulder
RB_1: {num: 6,  center: 385,range: 532,direction: -1, center_angle_deg:  -22.3} # hip
LB_3: {num: 7,  center: 221,range: 198,direction: -1, center_angle_deg:  -31.7} # knee
LB_2: {num: 8,  center: 500,range: 193,direction:  1, center_angle_deg:   55.7} # shoulder
LB_1: {num: 9,  center: 259,range: 557,direction:  1, center_angle_deg:  -22.5} # hip
LF_3: {num: 10, center: 229,range: 213,direction: -1, center_angle_deg:  -34.9} # knee
LF_2: {num: 11, center: 460,range: 233,direction:  1, center_angle_deg:   36.9} # shoulder
LF_1: {num: 12, center: 408,range: 565,direction: -1, center_angle_deg:  -22.5} # hip

# Control Parameters
transit_tau: 0.3 # Time constant in seconds for transition state first order filters
transit_rl: 0.06 # rate limit in m/s for transition state first order filters
transit_angle_rl: 0.35 # rate limit in rad/s for transition angle state first order filters

# Gait parameters
max_fwd_velocity: 0.4
max_side_velocity: 0.4
max_yaw_rate: 0.35
z_clearance: 0.045
alpha: 0.5
beta: 0.5
num_phases: 4
rb_contact_phases: [1, 0, 1, 1]
rf_contact_phases: [1, 1, 1, 0]
lf_contact_phases: [1, 0, 1, 1]
lb_contact_phases: [1, 1, 1, 0]
overlap_time: 0.2
swing_time: 0.20
foot_height_time_constant: 0.02
body_shift_phases: [0, 0, 0, 0]
fwd_body_balance_shift: 0.00
back_body_balance_shift: 0.00
side_body_balance_shift: 0.0

# Node parameters
dt: 0.02 #50 hz

# Debug mode
debug_mode: false
plot_mode: true

